POST http://localhost:3000/campaigns

{
  "name": "mouse",
  "content": "change password",
  "emails": ["email@example.com"]
}

###
GET http://localhost:3000/campaigns/ci9m0nq9m4s4tj66bbqg

###

PATCH http://localhost:3000/campaigns/cancel/ci9m0nq9m4s4tj66bbqg
